name: "single login"
version: "1.0.0"
mode: "dev"
port: 8888
start_time: "2020-11-23"
machine_id: 1

auth:
    jwt_atoken_expire: 1
    jwt_rtoken_expire: 5

log:
  level: "debug"
  filename: "./log/app.log"
  max_size: 200
  max_age: 30
  max_backups: 7
mysql:
  host: "127.0.0.1"
  port: 3306
  user: "root"
  password: "root123"
  dbname: "slogin"
  max_open_conns: 200
  max_idle_conns: 50
redis:
  host: "127.0.0.1"
  port: 6379
  password: ""
  db: 0
  pool_size: 100

jpush:
  master: "054e83378c2ef1bed6b41995"
  appkey: "c2c65fe9fc05f649becea714"
